# Cloudflare Pages Configuration
name = "baokaliao"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

# Environment variables (add your actual values in Cloudflare dashboard)
[vars]
# Add non-sensitive variables here
NODE_ENV = "production"

# For sensitive variables like API keys and database URLs,
# set them in the Cloudflare Pages dashboard under Settings > Environment variables
# Required variables:
# - DATABASE_URL
# - DIRECT_URL
# - NEXT_PUBLIC_SUPABASE_URL
# - NEXT_PUBLIC_SUPABASE_ANON_KEY
# - SUPABASE_SERVICE_ROLE_KEY
# - GOOGLE_MAPS_API_KEY
